module.exports = {
    compilerOptions: {
        target: 'es2020',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        noImplicitReturns: true,
        strict: true,
        forceConsistentCasingInFileNames: true,
        module: 'es2020',
        moduleResolution: 'node',
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: false,
        jsx: 'react',
        newLine: 'lf',
        baseUrl: 'src',
        paths: {
            // Import aliases like `import("@Public/img/myasset.png")`
            '@assets/*': ['assets/*', 'assets/index'],
            '@assets': ['assets/index'],
            '@components/*': ['components/*', 'components/index'],
            '@components': ['components/index'],
            '@layouts/*': ['layouts/*', 'layouts/index'],
            '@layouts': ['layouts/index'],
            '@models/*': ['models/*', 'models/index'],
            '@models': ['models/index'],
            '@pages/*': ['pages/*', 'pages/index'],
            '@pages': ['pages/index'],
            '@public/*': ['../public/*', 'public/index'],
            '@public': ['../public/index'],
            '@utils/*': ['utils/*', 'utils/index'],
            '@utils': ['utils/index'],
            '@/*': ['./*'],
            '~/*': ['../*'],
        },
    },
    include: ['src'],
    exclude: [
        'lib',
        'build',
        'node_modules',
        'scripts',
        'webpack',
        'jest',
        'tests',
        'templates',
    ],
};
